FROM python:3.9

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY main.py .

# ENV RABBITMQ_HOST=localhost
# ENV RABBITMQ_PORT=5672
# ENV RABBITMQ_USERNAME=guest
# ENV RABBITMQ_PASSWORD=guest
# ENV RABBITMQ_EXCHANGE=board
# ENV RABBITMQ_ROUTING_KEY=logs.*

CMD ["python", "rabbit.py"]
